---
- name: Configure Kubernetes Master
  hosts: k8s_master
  become: yes
  roles:
    - kubernetes_master

- name: Configure Kubernetes Network
  hosts: k8s_master
  become: yes
  roles:
    - kubernetes_network

- name: Configure Kubernetes Worker
  hosts: k8s_nodes
  become: yes
  roles:
    - kubernetes_worker